version: "3"
volumes:
    dbdata:
services:
  back:
    image: python:3
    volumes:
      - ./:/src
    working_dir: /src/back
    command: bash -c "pip install -U -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    ports: 
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes: 
      - dbdata:/var/lib/postgresql/data
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres