version: "3"
volumes:
    dbdata:
services:
  back:
    build: ./
    volumes:
      - ./:/src
    working_dir: /src/back
    command: ../wait-for-postgres.sh
    ports: 
      - 5000:5000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres:13
    volumes: 
      - dbdata:/var/lib/postgresql/data
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
